// <auto-generated />
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Exception thrown when an API request returns a non-success HTTP status code.
/// Inherits from <see cref="HttpRequestException"/> for backwards compatibility.
/// </summary>
public class ApiException : HttpRequestException
{
  /// <summary>HTTP method (GET/POST/PUT/PATCH/DELETE).</summary>
  public string Method { get; }

  /// <summary>Request URL (relative to the client base address).</summary>
  public string Url { get; }

  /// <summary>Raw response body as returned by the server.</summary>
  public string ResponseBody { get; }

  /// <summary>Response headers (status-line headers like Date, Server, X-Request-Id, etc.).</summary>
  public HttpResponseHeaders Headers { get; }

  /// <summary>Content headers (Content-Type, Content-Length, Content-Disposition, etc.).</summary>
  public HttpContentHeaders ContentHeaders { get; }

  public ApiException(
    HttpStatusCode statusCode,
    string method,
    string url,
    string responseBody,
    HttpResponseHeaders headers,
    HttpContentHeaders contentHeaders)
    : base($"{method} {url} failed with status {(int)statusCode} ({statusCode})", inner: null, statusCode: statusCode)
  {
    Method = method;
    Url = url;
    ResponseBody = responseBody;
    Headers = headers;
    ContentHeaders = contentHeaders;
  }
}
