// <auto-generated />
using Microsoft.Extensions.Logging;
using System;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// High-performance HTTP client logging using LoggerMessage source generator.
/// </summary>
internal static partial class HttpClientLog
{
  [LoggerMessage(EventId = 1001, Level = LogLevel.Debug,
    Message = "Making {Method} request to {Url}")]
  private static partial void LogDebugRequestStartedCore(ILogger logger, string method, string url);

  public static void LogDebugRequestStarted(ILogger? logger, string method, string url)
  {
    if (logger != null)
      LogDebugRequestStartedCore(logger, method, url);
  }

  [LoggerMessage(EventId = 1002, Level = LogLevel.Debug,
    Message = "Received {StatusCode} response from {Method} {Url} in {DurationMs}ms")]
  private static partial void LogDebugRequestCompletedCore(ILogger logger, int statusCode, string method, string url, long durationMs);

  public static void LogDebugRequestCompleted(ILogger? logger, int statusCode, string method, string url, long durationMs)
  {
    if (logger != null)
      LogDebugRequestCompletedCore(logger, statusCode, method, url, durationMs);
  }

  [LoggerMessage(EventId = 3001, Level = LogLevel.Error,
    Message = "HTTP {StatusCode} error for {Method} {Url}. Response: {ResponseContent}")]
  private static partial void LogErrorRequestFailedCore(ILogger logger, int statusCode, string method, string url, string responseContent, Exception? exception);

  public static void LogErrorRequestFailed(ILogger? logger, int statusCode, string method, string url, string responseContent, Exception? exception)
  {
    if (logger != null)
      LogErrorRequestFailedCore(logger, statusCode, method, url, responseContent, exception);
  }

  [LoggerMessage(EventId = 1003, Level = LogLevel.Trace,
    Message = "{Method} request body [{ContentType}]: {Body}")]
  private static partial void LogTraceRequestBodyCore(ILogger logger, string method, string contentType, string body);

  public static void LogTraceRequestBody(ILogger? logger, string method, string contentType, string body)
  {
    if (logger != null)
      LogTraceRequestBodyCore(logger, method, contentType, body);
  }

  [LoggerMessage(EventId = 2003, Level = LogLevel.Trace,
    Message = "Response from {Url}: {Body}")]
  private static partial void LogTraceResponseBodyCore(ILogger logger, string url, string body);

  public static void LogTraceResponseBody(ILogger? logger, string url, string body)
  {
    if (logger != null)
      LogTraceResponseBodyCore(logger, url, body);
  }
}
