// <auto-generated />
using System.ComponentModel;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Smart JSON converter for enhanced enums that handles both raw values and enum names.
/// </summary>
public class SmartEnumConverter<TEnum> : JsonConverter<TEnum?> where TEnum : struct, Enum
{
  private readonly Dictionary<string, TEnum> _stringToEnum;
  private readonly Dictionary<TEnum, string> _enumToString;
  private readonly TEnum? _unknownValue;

  public SmartEnumConverter()
  {
    _stringToEnum = BuildStringToEnumMapping();
    _enumToString = BuildEnumToStringMapping();
    _unknownValue = GetUnknownValue();
  }

  public override TEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
  {
    return reader.TokenType switch
    {
      JsonTokenType.String => ParseStringValue(reader.GetString()),
      JsonTokenType.Number => ParseNumberValue(reader),
      JsonTokenType.Null => null,
      _ => _unknownValue,
    };
  }

  public override void Write(Utf8JsonWriter writer, TEnum? value, JsonSerializerOptions options)
  {
    if (value == null)
    {
      writer.WriteNullValue();
      return;
    }

    if (_enumToString.TryGetValue(value.Value, out string? rawValue))
    {
      writer.WriteStringValue(rawValue);
    }
    else
    {
      writer.WriteStringValue(value.ToString());
    }
  }

  private TEnum? ParseStringValue(string? value)
  {
    if (string.IsNullOrEmpty(value))
    {
      return null;
    }

    if (_stringToEnum.TryGetValue(value, out TEnum exact))
    {
      return exact;
    }

    if (int.TryParse(value, out int numValue))
    {
      return ParseNumericValue(numValue);
    }

    if (Enum.TryParse<TEnum>(value, true, out TEnum parsed))
    {
      return parsed;
    }

    return _unknownValue;
  }

  private TEnum? ParseNumberValue(Utf8JsonReader reader)
  {
    if (reader.TryGetInt32(out int intValue))
    {
      return ParseNumericValue(intValue);
    }

    return _unknownValue;
  }

  private TEnum? ParseNumericValue(int value)
  {
    if (Enum.IsDefined(typeof(TEnum), value))
    {
      return (TEnum)(object)value;
    }

    string underscoreName = $"_{value}";
    if (_stringToEnum.TryGetValue(underscoreName, out TEnum prefixed))
    {
      return prefixed;
    }

    return _unknownValue;
  }

  private Dictionary<string, TEnum> BuildStringToEnumMapping()
  {
    Dictionary<string, TEnum> mapping = new(StringComparer.OrdinalIgnoreCase);

    foreach (TEnum enumValue in Enum.GetValues<TEnum>())
    {
      string enumName = enumValue.ToString();
      mapping[enumName] = enumValue;

      FieldInfo? memberInfo = typeof(TEnum).GetField(enumName);
      EnumMemberAttribute? enumMemberAttr = memberInfo?.GetCustomAttribute<EnumMemberAttribute>();
      if (enumMemberAttr?.Value != null)
      {
        mapping[enumMemberAttr.Value] = enumValue;
      }

      if (enumName.StartsWith("_") && int.TryParse(enumName.Substring(1), out int numericValue))
      {
        mapping[numericValue.ToString()] = enumValue;
      }
    }

    return mapping;
  }

  private Dictionary<TEnum, string> BuildEnumToStringMapping()
  {
    Dictionary<TEnum, string> mapping = new();

    foreach (TEnum enumValue in Enum.GetValues<TEnum>())
    {
      string enumName = enumValue.ToString();

      FieldInfo? memberInfo = typeof(TEnum).GetField(enumName);
      EnumMemberAttribute? enumMemberAttr = memberInfo?.GetCustomAttribute<EnumMemberAttribute>();

      if (enumMemberAttr?.Value != null)
      {
        mapping[enumValue] = enumMemberAttr.Value;
      }
      else if (enumName.StartsWith("_") && int.TryParse(enumName.Substring(1), out int numericValue))
      {
        mapping[enumValue] = numericValue.ToString();
      }
      else
      {
        mapping[enumValue] = enumName;
      }
    }

    return mapping;
  }

  private TEnum? GetUnknownValue()
  {
    if (Enum.TryParse<TEnum>("Unknown", true, out TEnum unknown))
    {
      return unknown;
    }

    if (Enum.IsDefined(typeof(TEnum), -1))
    {
      return (TEnum)(object)-1;
    }

    TEnum[] values = Enum.GetValues<TEnum>();
    return values.Length > 0 ? values[0] : null;
  }
}

/// <summary>
/// Non-nullable version of the smart enum converter.
/// </summary>
public class SmartEnumConverterNonNullable<TEnum> : JsonConverter<TEnum> where TEnum : struct, Enum
{
  private readonly SmartEnumConverter<TEnum> _nullableConverter = new();

  public override TEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
  {
    return _nullableConverter.Read(ref reader, typeToConvert, options) ?? default(TEnum);
  }

  public override void Write(Utf8JsonWriter writer, TEnum value, JsonSerializerOptions options)
  {
    _nullableConverter.Write(writer, value, options);
  }
}

/// <summary>
/// Factory for creating smart enum converters.
/// </summary>
public class SmartEnumConverterFactory : JsonConverterFactory
{
  public override bool CanConvert(Type typeToConvert)
  {
    return typeToConvert.IsEnum ||
           (typeToConvert.IsGenericType &&
            typeToConvert.GetGenericTypeDefinition() == typeof(Nullable<>) &&
            typeToConvert.GetGenericArguments()[0].IsEnum);
  }

  public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
  {
    if (typeToConvert.IsEnum)
    {
      return (JsonConverter)Activator.CreateInstance(
        typeof(SmartEnumConverterNonNullable<>).MakeGenericType(typeToConvert))!;
    }
    else
    {
      Type enumType = typeToConvert.GetGenericArguments()[0];
      return (JsonConverter)Activator.CreateInstance(
        typeof(SmartEnumConverter<>).MakeGenericType(enumType))!;
    }
  }
}
