//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Vikunja.Models;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Interface for admin operations
/// </summary>
public partial interface IAdminClient
{
  /// <summary>
  /// Admin overview
  /// Operation: GET /admin/overview
  /// </summary>
  Task<Overview> GetadminAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// List projects (admin)
  /// Operation: GET /admin/projects
  /// </summary>
  Task<List<Project>> GetAdminProjectsAsync(GetadminRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Reassign project owner (admin)
  /// Operation: PATCH /admin/projects/{id}/owner
  /// </summary>
  Task<Project> PatchadminAsync(int id, Apigen.Vikunja.Models.AdminDotOwnerPatchPatchRequest adminDotOwnerPatchPatchRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List users (admin)
  /// Operation: GET /admin/users
  /// </summary>
  Task<List<SharedDotAdminUser>> GetAdminUsersAsync(GetadminRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a user (admin)
  /// Operation: POST /admin/users
  /// </summary>
  Task<SharedDotAdminUser> PostadminAsync(Apigen.Vikunja.Models.CreateUserBody createUserBody, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete a user (admin)
  /// Operation: DELETE /admin/users/{id}
  /// </summary>
  Task DeleteadminAsync(int id, DeleteadminRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Promote or demote a user (admin)
  /// Operation: PATCH /admin/users/{id}/admin
  /// </summary>
  Task<SharedDotAdminUser> PatchadminAsync(int id, Apigen.Vikunja.Models.AdminDotIsAdminPatchPatchRequest adminDotIsAdminPatchPatchRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Set a user&apos;s status (admin)
  /// Operation: PATCH /admin/users/{id}/status
  /// </summary>
  Task<SharedDotAdminUser> PatchadminAsync(int id, Apigen.Vikunja.Models.AdminDotStatusPatchPatchRequest adminDotStatusPatchPatchRequest, CancellationToken cancellationToken = default);

}
