//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Vikunja.Models;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Interface for filter operations
/// </summary>
public partial interface IFilterClient
{
  /// <summary>
  /// Creates a new saved filter
  /// Operation: PUT /filters
  /// </summary>
  Task<SavedFilter> CreateFilterAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Gets one saved filter
  /// Operation: GET /filters/{id}
  /// </summary>
  Task<SavedFilter> GetfilterAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates a saved filter
  /// Operation: POST /filters/{id}
  /// </summary>
  Task<SavedFilter> UpdateFilterAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Removes a saved filter
  /// Operation: DELETE /filters/{id}
  /// </summary>
  Task<SavedFilter> DeletefilterAsync(int id, CancellationToken cancellationToken = default);

}
