//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Vikunja.Models;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Interface for migration operations
/// </summary>
public partial interface IMigrationClient
{
  /// <summary>
  /// Detect CSV structure
  /// Operation: PUT /migration/csv/detect
  /// </summary>
  Task<CsvDetectionResult> DetectCsvStructureAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Import CSV file
  /// Operation: PUT /migration/csv/migrate
  /// </summary>
  Task<Message> MigrateFromCsvAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Preview CSV import
  /// Operation: PUT /migration/csv/preview
  /// </summary>
  Task<CsvPreviewResult> PreviewCsvImportAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get CSV migration status
  /// Operation: GET /migration/csv/status
  /// </summary>
  Task<Status> GetCsvMigrationStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the auth url from Microsoft Todo
  /// Operation: GET /migration/microsoft-todo/auth
  /// </summary>
  Task<AuthUrl> GetmigrationAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Migrate all projects, tasks etc. from Microsoft Todo
  /// Operation: POST /migration/microsoft-todo/migrate
  /// </summary>
  Task<Message> MigrateFromMicrosoftTodoAsync(Apigen.Vikunja.Models.MicrosoftTodoMigration microsoftTodoMigration, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/microsoft-todo/status
  /// </summary>
  Task<Status> GetMigrationMicrosoftTodoStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Import all projects, tasks etc. from a TickTick backup export
  /// Operation: PUT /migration/ticktick/migrate
  /// </summary>
  Task<Message> PutmigrationAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/ticktick/status
  /// </summary>
  Task<Status> GetMigrationTicktickStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the auth url from todoist
  /// Operation: GET /migration/todoist/auth
  /// </summary>
  Task<AuthUrl> GetMigrationTodoistAuthAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Migrate all lists, tasks etc. from todoist
  /// Operation: POST /migration/todoist/migrate
  /// </summary>
  Task<Message> MigrateFromTodoistAsync(Apigen.Vikunja.Models.TodoistMigration todoistMigration, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/todoist/status
  /// </summary>
  Task<Status> GetMigrationTodoistStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get the auth url from trello
  /// Operation: GET /migration/trello/auth
  /// </summary>
  Task<AuthUrl> GetMigrationTrelloAuthAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Migrate all projects, tasks etc. from trello
  /// Operation: POST /migration/trello/migrate
  /// </summary>
  Task<Message> MigrateFromTrelloAsync(Apigen.Vikunja.Models.TrelloMigration trelloMigration, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/trello/status
  /// </summary>
  Task<Status> GetMigrationTrelloStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Import all projects, tasks etc. from a Vikunja data export
  /// Operation: POST /migration/vikunja-file/migrate
  /// </summary>
  Task<Message> PostmigrationAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/vikunja-file/status
  /// </summary>
  Task<Status> GetMigrationVikunjaFileStatusAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Import all projects, tasks etc. from a WeKan board export
  /// Operation: PUT /migration/wekan/migrate
  /// </summary>
  Task<Message> MigrateFromWekanAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Get migration status
  /// Operation: GET /migration/wekan/status
  /// </summary>
  Task<Status> GetWekanMigrationStatusAsync(CancellationToken cancellationToken = default);

}
