//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Vikunja.Models;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Interface for service operations
/// </summary>
public partial interface IServiceClient
{
  /// <summary>
  /// Info
  /// Operation: GET /info
  /// </summary>
  Task<SharedDotVikunjaInfos> GetserviceAsync(CancellationToken cancellationToken = default);

}
