//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Vikunja.Models;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Interface for subscriptions operations
/// </summary>
public partial interface ISubscriptionsClient
{
  /// <summary>
  /// Get all notifications for the current user
  /// Operation: GET /notifications
  /// </summary>
  Task<List<DatabaseNotification>> GetsubscriptionsAsync(GetsubscriptionsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete all notifications of the current user
  /// Operation: DELETE /notifications
  /// </summary>
  Task<Message> DeletesubscriptionsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Mark a notification as (un-)read
  /// Operation: POST /notifications/{id}
  /// </summary>
  Task<DatabaseNotifications> MarkNotificationReadAsync(int id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Subscribes the current user to an entity.
  /// Operation: PUT /subscriptions/{entity}/{entityID}
  /// </summary>
  Task<Subscription> SubscribeAsync(string entity, string entityId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Unsubscribe the current user from an entity.
  /// Operation: DELETE /subscriptions/{entity}/{entityID}
  /// </summary>
  Task<Subscription> DeletesubscriptionsAsync(string entity, string entityId, CancellationToken cancellationToken = default);

}
