//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Extension methods for building query strings and URL templates
/// </summary>
public static class QueryStringExtensions
{
  /// <summary>
  /// Converts a dictionary of query parameters to a URL-encoded query string
  /// </summary>
  /// <param name="queryParams">Dictionary of query parameters</param>
  /// <returns>URL-encoded query string starting with '?' or empty string if no parameters</returns>
  public static string ToQueryString(this Dictionary<string, object> queryParams)
  {
    if (queryParams.Count == 0) return string.Empty;

    List<string> encodedParams = new List<string>();

    foreach (KeyValuePair<string, object> kvp in queryParams)
    {
      string encodedKey = HttpUtility.UrlEncode(kvp.Key);

      // Collections repeat the key: ?tag=1&tag=2
      if (kvp.Value is not string && kvp.Value is IEnumerable collection)
      {
        foreach (object? item in collection)
        {
          if (item == null) continue;
          encodedParams.Add($"{encodedKey}={HttpUtility.UrlEncode(FormatValue(item))}");
        }

        continue;
      }

      encodedParams.Add($"{encodedKey}={HttpUtility.UrlEncode(FormatValue(kvp.Value))}");
    }

    if (encodedParams.Count == 0) return string.Empty;

    return "?" + string.Join("&", encodedParams);
  }

  /// <summary>
  /// Joins a collection into a single query value, for parameters that do not explode
  /// (OpenAPI style form/spaceDelimited/pipeDelimited with explode: false).
  /// </summary>
  public static string Join(IEnumerable values, string separator)
  {
    List<string> formatted = new List<string>();
    foreach (object? item in values)
    {
      if (item == null) continue;
      formatted.Add(FormatValue(item));
    }

    return string.Join(separator, formatted);
  }

  /// <summary>
  /// Formats a single value for use in a URL. Dates are written as ISO 8601 and
  /// booleans lowercase; numbers use invariant culture so a comma never sneaks in.
  /// </summary>
  private static string FormatValue(object? value) => value switch
  {
    null => string.Empty,
    string s => s,
    bool b => b ? "true" : "false",
    DateTimeOffset dto => dto.ToString("o", CultureInfo.InvariantCulture),
    DateTime dt => dt.ToString("o", CultureInfo.InvariantCulture),
    DateOnly d => d.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
    TimeOnly t => t.ToString("HH:mm:ss", CultureInfo.InvariantCulture),
    IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
    _ => value.ToString() ?? string.Empty
  };

  /// <summary>
  /// Builds a URL from a template string by safely substituting parameters and appending query string
  /// </summary>
  /// <param name="template">URL template with {param} placeholders (case-sensitive)</param>
  /// <param name="pathParams">Dictionary with path parameter values. Keys must match template placeholders exactly.</param>
  /// <param name="request">Request object with ToQueryString method for query parameters</param>
  /// <returns>Complete URL with path parameters substituted and query string appended</returns>
  public static string BuildUrl(this string template, Dictionary<string, object>? pathParams = null, object? request = null, ICollection<string>? pathSegmentParameters = null)
  {
    string url = template;

    // Handle path parameter substitution
    if (pathParams != null)
    {
      // Dictionary keys must match template placeholders exactly (case-sensitive)

      StringBuilder result = new StringBuilder();
      int lastIndex = 0;

      while (lastIndex < template.Length)
      {
        int openBrace = template.IndexOf('{', lastIndex);
        if (openBrace == -1)
        {
          // No more placeholders, append the rest
          result.Append(template.Substring(lastIndex));
          break;
        }

        // Append literal part before the placeholder
        result.Append(template.Substring(lastIndex, openBrace - lastIndex));

        int closeBrace = template.IndexOf('}', openBrace);
        if (closeBrace == -1)
        {
          // Malformed template, append the rest as-is
          result.Append(template.Substring(openBrace));
          break;
        }

        // Extract parameter name and substitute
        string paramName = template.Substring(openBrace + 1, closeBrace - openBrace - 1);
        if (pathParams.TryGetValue(paramName, out object? paramValue))
        {
          if (pathSegmentParameters?.Contains(paramName) == true)
          {
            string[] segments = FormatValue(paramValue).Split('/', StringSplitOptions.RemoveEmptyEntries);
            if (Array.Exists(segments, segment => segment is "." or ".."))
              throw new ArgumentException("Path segments cannot be '.' or '..'.", paramName);
            result.Append(string.Join("/", Array.ConvertAll(segments, Uri.EscapeDataString)));
            if (segments.Length == 0 && result.Length > 0 && result[result.Length - 1] == '/' && closeBrace + 1 < template.Length && template[closeBrace + 1] == '/')
              closeBrace++;
          }
          else
          {
            result.Append(Uri.EscapeDataString(FormatValue(paramValue)));
          }
        }
        else
        {
          // Parameter not found, keep placeholder
          result.Append(template.Substring(openBrace, closeBrace - openBrace + 1));
        }

        lastIndex = closeBrace + 1;
      }

      url = result.ToString();
    }

    // Handle query string appending
    if (request != null)
    {
      MethodInfo? toQueryStringMethod = request.GetType().GetMethod("ToQueryString");
      if (toQueryStringMethod != null)
      {
        string? queryString = toQueryStringMethod.Invoke(request, null) as string;
        if (!string.IsNullOrEmpty(queryString))
        {
          url += queryString;
        }
      }
    }

    return url;
  }
}
