//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.APIToken from OpenAPI schema.
/// Schema path: #/components/schemas/models.APIToken
/// </summary>
public partial class ApiToken
{
  /// <summary>
  /// A timestamp when this api key was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The date when this key expires.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expires_at")]
  public string? ExpiresAt { get; set; }

  /// <summary>
  /// The unique, numeric id of this api key.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The user ID of the token owner. When creating a token for a bot user, set this
  /// to the bot&apos;s ID. If omitted, defaults to the authenticated user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("owner_id")]
  public int? OwnerId { get; set; }

  /// <summary>
  /// The permissions this token has. Possible values are available via the /routes endpoint and consist of the keys of the list from that endpoint. For example, if the token should be able to read all tasks as well as update existing tasks, you should add {&quot;tasks&quot;:[&quot;read_all&quot;,&quot;update&quot;]}.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public ApiPermissions? Permissions { get; set; }

  /// <summary>
  /// A human-readable name for this token
  /// </summary>
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// The actual api key. Only visible after creation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }
}
