//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// handler.AuthURL from OpenAPI schema.
/// Schema path: #/components/schemas/handler.AuthURL
/// </summary>
public partial class AuthUrl
{
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }
}
