//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Bucket from OpenAPI schema.
/// Schema path: #/components/schemas/models.Bucket
/// </summary>
public class Bucket
{
  /// <summary>
  /// The number of tasks currently in this bucket
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public int? Count { get; set; }

  /// <summary>
  /// A timestamp when this bucket was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who initially created the bucket.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The unique, numeric id of this bucket.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// How many tasks can be at the same time on this board max
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("limit")]
  public int? Limit { get; set; }

  /// <summary>
  /// The position this bucket has when querying all buckets. See the tasks.position property on how to use this.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("position")]
  public decimal? Position { get; set; }

  /// <summary>
  /// The project view this bucket belongs to.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_view_id")]
  public int? ProjectViewId { get; set; }

  /// <summary>
  /// All tasks which belong to this bucket.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tasks")]
  public List<TaskItem>? Tasks { get; set; }

  /// <summary>
  /// The title of this bucket.
  /// </summary>
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this bucket was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
