//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.BulkTask from OpenAPI schema.
/// Schema path: #/components/schemas/models.BulkTask
/// </summary>
public class BulkTask
{
  [System.Text.Json.Serialization.JsonPropertyName("fields")]
  public List<string?>? Fields { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_ids")]
  public List<int>? TaskIds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tasks")]
  public List<TaskItem>? Tasks { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("values")]
  public TaskItem? Values { get; set; }
}
