//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// openid.Callback from OpenAPI schema.
/// Schema path: #/components/schemas/openid.Callback
/// </summary>
public partial class Callback
{
  [System.Text.Json.Serialization.JsonPropertyName("code")]
  public string? Code { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("redirect_url")]
  public string? RedirectUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }

  /// <summary>
  /// TOTPPasscode is required when the resolved user has TOTP enabled.
  /// Clients must restart the OIDC flow and populate this field after
  /// receiving a 412 with error code 1017. See GHSA-8jvc-mcx6-r4cg.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("totp_passcode")]
  public string? TotpPasscode { get; set; }
}
