//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.CreateUserBody from OpenAPI schema.
/// Schema path: #/components/schemas/models.CreateUserBody
/// </summary>
public partial class CreateUserBody
{
  /// <summary>
  /// The user&apos;s email address
  /// </summary>
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// Mark the new user as an instance admin.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_admin")]
  public bool? IsAdmin { get; set; }

  /// <summary>
  /// The language of the new user. Must be a valid IETF BCP 47 language code and exist in Vikunja.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  /// <summary>
  /// The full name of the new user. Optional.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The user&apos;s password in clear text. Only used when registering the user. The maximum limi is 72 bytes, which may be less than 72 characters. This is due to the limit in the bcrypt hashing algorithm used to store passwords in Vikunja.
  /// </summary>
  [MinLength(8)]
  [MaxLength(72)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// Activate the new user immediately without email confirmation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("skip_email_confirm")]
  public bool? SkipEmailConfirm { get; set; }

  /// <summary>
  /// The user&apos;s username. Cannot contain anything that looks like an url or whitespaces.
  /// </summary>
  [MinLength(3)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
