//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// csv.DetectionResult from OpenAPI schema.
/// Schema path: #/components/schemas/csv.DetectionResult
/// </summary>
public partial class CsvDetectionResult
{
  [System.Text.Json.Serialization.JsonPropertyName("columns")]
  public List<string?>? Columns { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("date_format")]
  public string? DateFormat { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("delimiter")]
  public string? Delimiter { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("preview_rows")]
  public List<List<string?>?>? PreviewRows { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("quote_char")]
  public string? QuoteChar { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("suggested_mapping")]
  public List<CsvColumnMapping>? SuggestedMapping { get; set; }
}
