//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// csv.PreviewTask from OpenAPI schema.
/// Schema path: #/components/schemas/csv.PreviewTask
/// </summary>
public class CsvPreviewTask
{
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("done")]
  public bool? Done { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("due_date")]
  public string? DueDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("end_date")]
  public string? EndDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public List<string?>? Labels { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("project")]
  public string? Project { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("start_date")]
  public string? StartDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }
}
