//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Vikunja.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CsvTaskAttribute
{
    [JsonStringEnumMemberName("title")]
    Title,
    [JsonStringEnumMemberName("description")]
    Description,
    [JsonStringEnumMemberName("due_date")]
    DueDate,
    [JsonStringEnumMemberName("start_date")]
    StartDate,
    [JsonStringEnumMemberName("end_date")]
    EndDate,
    [JsonStringEnumMemberName("done")]
    Done,
    [JsonStringEnumMemberName("priority")]
    Priority,
    [JsonStringEnumMemberName("labels")]
    Labels,
    [JsonStringEnumMemberName("project")]
    Project,
    [JsonStringEnumMemberName("reminder")]
    Reminder,
    [JsonStringEnumMemberName("ignore")]
    Ignore,
}
