//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.DatabaseNotifications from OpenAPI schema.
/// Schema path: #/components/schemas/models.DatabaseNotifications
/// </summary>
public partial class DatabaseNotifications
{
  /// <summary>
  /// A timestamp when this notification was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The unique, numeric id of this notification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The name of the notification
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The actual content of the notification.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("notification")]
  public object? Notification { get; set; }

  /// <summary>
  /// Whether or not to mark this notification as read or unread.
  /// True is read, false is unread.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("read")]
  public bool? Read { get; set; }

  /// <summary>
  /// When this notification is marked as read, this will be updated with the current timestamp.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("read_at")]
  public string? ReadAt { get; set; }
}
