//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// user.EmailUpdate from OpenAPI schema.
/// Schema path: #/components/schemas/user.EmailUpdate
/// </summary>
public class EmailUpdate
{
  /// <summary>
  /// The new email address. Needs to be a valid email address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("new_email")]
  public string? NewEmail { get; set; }

  /// <summary>
  /// The password of the user for confirmation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }
}
