//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// web.HTTPError from OpenAPI schema.
/// Schema path: #/components/schemas/web.HTTPError
/// </summary>
public partial class HttpError
{
  [System.Text.Json.Serialization.JsonPropertyName("code")]
  public int? Code { get; set; }

  /// <summary>
  /// I18nParams carries Message&apos;s dynamic values, keyed by the client&apos;s translation placeholder names, so clients can localise the error.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("i18n_params")]
  public Dictionary<string, string?>? I18NParams { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }
}
