//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// background.Image from OpenAPI schema.
/// Schema path: #/components/schemas/background.Image
/// </summary>
public class Image
{
  [System.Text.Json.Serialization.JsonPropertyName("blur_hash")]
  public string? BlurHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// This can be used to supply extra information from an image provider to clients
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("info")]
  public object? Info { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("thumb")]
  public string? Thumb { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }
}
