//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.LabelTask from OpenAPI schema.
/// Schema path: #/components/schemas/models.LabelTask
/// </summary>
public partial class LabelTask
{
  /// <summary>
  /// A timestamp when this task was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The label id you want to associate with a task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("label_id")]
  public int? LabelId { get; set; }
}
