//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.LabelTaskBulk from OpenAPI schema.
/// Schema path: #/components/schemas/models.LabelTaskBulk
/// </summary>
public class LabelTaskBulk
{
  /// <summary>
  /// All labels you want to update at once.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public List<Label>? Labels { get; set; }
}
