//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Label from OpenAPI schema.
/// Schema path: #/components/schemas/models.Label
/// </summary>
public class Label
{
  /// <summary>
  /// A timestamp when this label was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who created this label
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The label description.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The color this label has in hex format.
  /// </summary>
  [MaxLength(7)]
  [System.Text.Json.Serialization.JsonPropertyName("hex_color")]
  public string? HexColor { get; set; }

  /// <summary>
  /// The unique, numeric id of this label.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The title of the label. You&apos;ll see this one on tasks associated with it.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this label was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
