//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Vikunja.Models;

[JsonConverter(typeof(JsonNumberEnumConverter<LicenseDotFeature>))]
public enum LicenseDotFeature
{
    FeatureUnknown = 0,
    FeatureAdminPanel = 1,
    FeatureTimeTracking = 2,
    FeatureAuditLogs = 3,
}
