//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// license.Info from OpenAPI schema.
/// Schema path: #/components/schemas/license.Info
/// </summary>
public partial class LicenseDotInfo
{
  [System.Text.Json.Serialization.JsonPropertyName("expires_at")]
  public string? ExpiresAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("features")]
  public List<string?>? Features { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("instance_id")]
  public string? InstanceId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("last_check_failed")]
  public bool? LastCheckFailed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("licensed")]
  public bool? Licensed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_users")]
  public int? MaxUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("validated_at")]
  public string? ValidatedAt { get; set; }
}
