//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.LinkSharing from OpenAPI schema.
/// Schema path: #/components/schemas/models.LinkSharing
/// </summary>
public class LinkSharing
{
  /// <summary>
  /// A timestamp when this project was shared. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The public id to get this shared project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hash")]
  public string? Hash { get; set; }

  /// <summary>
  /// The ID of the shared thing
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The name of this link share. All actions someone takes while being authenticated with that link will appear with that name.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The password of this link share. You can only set it, not retrieve it after the link share has been created.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The permission this project is shared with. 0 = Read only, 1 = Read &amp; Write, 2 = Admin. See the docs for more details.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("permission")]
  public Permission? Permission { get; set; }

  /// <summary>
  /// The user who shared this project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("shared_by")]
  public User? SharedBy { get; set; }

  /// <summary>
  /// The kind of this link. 0 = undefined, 1 = without password, 2 = with password.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sharing_type")]
  public SharingType? SharingType { get; set; }

  /// <summary>
  /// A timestamp when this share was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
