//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// user.Login from OpenAPI schema.
/// Schema path: #/components/schemas/user.Login
/// </summary>
public class Login
{
  /// <summary>
  /// If true, the token returned will be valid a lot longer than default. Useful for &quot;remember me&quot; style logins.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("long_token")]
  public bool? LongToken { get; set; }

  /// <summary>
  /// The password for the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The totp passcode of a user. Only needs to be provided when enabled.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("totp_passcode")]
  public string? TotpPasscode { get; set; }

  /// <summary>
  /// The username used to log in.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
