//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.LogoutResponse from OpenAPI schema.
/// Schema path: #/components/schemas/v1.LogoutResponse
/// </summary>
public partial class LogoutResponse
{
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  /// <summary>
  /// RP-Initiated Logout URL the frontend redirects to. Empty for non-OIDC sessions.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("oidc_logout_url")]
  public string? OidcLogoutUrl { get; set; }
}
