//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
}
