//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// code_vikunja_io_api_pkg_modules_auth_openid.Provider from OpenAPI schema.
/// Schema path: #/components/schemas/code_vikunja_io_api_pkg_modules_auth_openid.Provider
/// </summary>
public class OpenIdProvider
{
  [System.Text.Json.Serialization.JsonPropertyName("auth_url")]
  public string? AuthUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email_fallback")]
  public bool? EmailFallback { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("force_user_info")]
  public bool? ForceUserInfo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("logout_url")]
  public string? LogoutUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("username_fallback")]
  public bool? UsernameFallback { get; set; }
}
