//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Overview from OpenAPI schema.
/// Schema path: #/components/schemas/models.Overview
/// </summary>
public partial class Overview
{
  [System.Text.Json.Serialization.JsonPropertyName("license")]
  public LicenseDotInfo? License { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("projects")]
  public int? Projects { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("shares")]
  public ShareCounts? Shares { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tasks")]
  public int? Tasks { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("teams")]
  public int? Teams { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("users")]
  public int? Users { get; set; }
}
