//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// user.PasswordReset from OpenAPI schema.
/// Schema path: #/components/schemas/user.PasswordReset
/// </summary>
public partial class PasswordReset
{
  /// <summary>
  /// The new password for this user.
  /// </summary>
  [MinLength(8)]
  [MaxLength(72)]
  [System.Text.Json.Serialization.JsonPropertyName("new_password")]
  public string? NewPassword { get; set; }

  /// <summary>
  /// The previously issued reset token.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }
}
