//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.ProjectViewBucketConfiguration from OpenAPI schema.
/// Schema path: #/components/schemas/models.ProjectViewBucketConfiguration
/// </summary>
public class ProjectViewBucketConfiguration
{
  [System.Text.Json.Serialization.JsonPropertyName("filter")]
  public TaskCollection? Filter { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }
}
