//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.ProjectView from OpenAPI schema.
/// Schema path: #/components/schemas/models.ProjectView
/// </summary>
public class ProjectView
{
  /// <summary>
  /// When the bucket configuration mode is not manual, this field holds the options of that configuration.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bucket_configuration")]
  public List<ProjectViewBucketConfiguration>? BucketConfiguration { get; set; }

  /// <summary>
  /// The bucket configuration mode. Can be none, manual or filter. manual allows to move tasks between buckets as you normally would. filter creates buckets based on a filter for each bucket.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bucket_configuration_mode")]
  public string? BucketConfigurationMode { get; set; }

  /// <summary>
  /// A timestamp when this reaction was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The ID of the bucket where new tasks without a bucket are added to. By default, this is the leftmost bucket in a view.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("default_bucket_id")]
  public int? DefaultBucketId { get; set; }

  /// <summary>
  /// If tasks are moved to the done bucket, they are marked as done. If they are marked as done individually, they are moved into the done bucket.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("done_bucket_id")]
  public int? DoneBucketId { get; set; }

  /// <summary>
  /// The filter query to match tasks by. Check out https://vikunja.io/docs/filters for a full explanation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filter")]
  public TaskCollection? Filter { get; set; }

  /// <summary>
  /// The unique numeric id of this view
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The position of this view in the list. The list of all views will be sorted by this parameter.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("position")]
  public decimal? Position { get; set; }

  /// <summary>
  /// The project this view belongs to
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public int? ProjectId { get; set; }

  /// <summary>
  /// The title of this view
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this view was updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }

  /// <summary>
  /// The kind of this view. Can be list, gantt, table or kanban.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("view_kind")]
  public string? ViewKind { get; set; }
}
