//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.ProjectDuplicate from OpenAPI schema.
/// Schema path: #/components/schemas/models.ProjectDuplicate
/// </summary>
public partial class ProjectDuplicate
{
  /// <summary>
  /// The copied project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("duplicated_project")]
  public Project? DuplicatedProject { get; set; }

  /// <summary>
  /// The target parent project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("parent_project_id")]
  public int? ParentProjectId { get; set; }
}
