//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Project from OpenAPI schema.
/// Schema path: #/components/schemas/models.Project
/// </summary>
public partial class Project
{
  /// <summary>
  /// Contains a very small version of the project background to use as a blurry preview until the actual background is loaded. Check out https://blurha.sh/ to learn how it works.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("background_blur_hash")]
  public string? BackgroundBlurHash { get; set; }

  /// <summary>
  /// Holds extra information about the background set since some background providers require attribution or similar. If not null, the background can be accessed at /projects/{projectID}/background
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("background_information")]
  public object? BackgroundInformation { get; set; }

  /// <summary>
  /// A timestamp when this project was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The description of the project.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The hex color of this project
  /// </summary>
  [MaxLength(7)]
  [System.Text.Json.Serialization.JsonPropertyName("hex_color")]
  public string? HexColor { get; set; }

  /// <summary>
  /// The unique, numeric id of this project.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The unique project short identifier. Used to build task identifiers.
  /// </summary>
  [MinLength(0)]
  [MaxLength(10)]
  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  /// <summary>
  /// Whether a project is archived.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_archived")]
  public bool? IsArchived { get; set; }

  /// <summary>
  /// True if a project is a favorite. Favorite projects show up in a separate parent project. This value depends on the user making the call to the api.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_favorite")]
  public bool? IsFavorite { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_permission")]
  public Permission? MaxPermission { get; set; }

  /// <summary>
  /// The user who created this project.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public User? Owner { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("parent_project_id")]
  public int? ParentProjectId { get; set; }

  /// <summary>
  /// The position this project has when querying all projects. See the tasks.position property on how to use this.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("position")]
  public decimal? Position { get; set; }

  /// <summary>
  /// The subscription status for the user reading this project. You can only read this property, use the subscription endpoints to modify it.
  /// Will only returned when retreiving one project.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("subscription")]
  public Subscription? Subscription { get; set; }

  /// <summary>
  /// The title of the project. You&apos;ll see this in the overview.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this project was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("views")]
  public List<ProjectView>? Views { get; set; }
}
