//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Reaction from OpenAPI schema.
/// Schema path: #/components/schemas/models.Reaction
/// </summary>
public class Reaction
{
  /// <summary>
  /// A timestamp when this reaction was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who reacted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public User? User { get; set; }

  /// <summary>
  /// The actual reaction. This can be any valid utf character or text, up to a length of 20.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
