//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Vikunja.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RelationKind
{
    [JsonStringEnumMemberName("unknown")]
    Unknown,
    [JsonStringEnumMemberName("subtask")]
    Subtask,
    [JsonStringEnumMemberName("parenttask")]
    Parenttask,
    [JsonStringEnumMemberName("related")]
    Related,
    [JsonStringEnumMemberName("duplicateof")]
    Duplicateof,
    [JsonStringEnumMemberName("duplicates")]
    Duplicates,
    [JsonStringEnumMemberName("blocking")]
    Blocking,
    [JsonStringEnumMemberName("blocked")]
    Blocked,
    [JsonStringEnumMemberName("precedes")]
    Precedes,
    [JsonStringEnumMemberName("follows")]
    Follows,
    [JsonStringEnumMemberName("copiedfrom")]
    Copiedfrom,
    [JsonStringEnumMemberName("copiedto")]
    Copiedto,
}
