//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.SavedFilter from OpenAPI schema.
/// Schema path: #/components/schemas/models.SavedFilter
/// </summary>
public class SavedFilter
{
  /// <summary>
  /// A timestamp when this filter was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The description of the filter
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The actual filters this filter contains
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filters")]
  public TaskCollection? Filters { get; set; }

  /// <summary>
  /// The unique numeric id of this saved filter
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// True if the filter is a favorite. Favorite filters show up in a separate parent project together with favorite projects.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_favorite")]
  public bool? IsFavorite { get; set; }

  /// <summary>
  /// The user who owns this filter
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public User? Owner { get; set; }

  /// <summary>
  /// The title of the filter.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this filter was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
