//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// shared.VikunjaInfos from OpenAPI schema.
/// Schema path: #/components/schemas/shared.VikunjaInfos
/// </summary>
public partial class SharedDotVikunjaInfos
{
  [System.Text.Json.Serialization.JsonPropertyName("allow_icon_changes")]
  public bool? AllowIconChanges { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("auth")]
  public SharedDotAuthInfo? Auth { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("available_migrators")]
  public List<string?>? AvailableMigrators { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("caldav_enabled")]
  public bool? CaldavEnabled { get; set; }

  /// <summary>
  /// ConcurrentWrites reports whether the configured database can handle concurrent writes. It is false on SQLite, where overlapping write transactions deadlock, so clients should serialize batched writes instead of firing them in parallel.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("concurrent_writes")]
  public bool? ConcurrentWrites { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("demo_mode_enabled")]
  public bool? DemoModeEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email_reminders_enabled")]
  public bool? EmailRemindersEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled_background_providers")]
  public List<string?>? EnabledBackgroundProviders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled_pro_features")]
  public List<LicenseDotFeature>? EnabledProFeatures { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("frontend_url")]
  public string? FrontendUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("legal")]
  public SharedDotLegalInfo? Legal { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("link_sharing_enabled")]
  public bool? LinkSharingEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_file_size")]
  public string? MaxFileSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_items_per_page")]
  public int? MaxItemsPerPage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("motd")]
  public string? Motd { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("public_teams_enabled")]
  public bool? PublicTeamsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_attachments_enabled")]
  public bool? TaskAttachmentsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_comments_enabled")]
  public bool? TaskCommentsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totp_enabled")]
  public bool? TotpEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user_deletion_enabled")]
  public bool? UserDeletionEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webhooks_enabled")]
  public bool? WebhooksEnabled { get; set; }
}
