//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.ShareCounts from OpenAPI schema.
/// Schema path: #/components/schemas/models.ShareCounts
/// </summary>
public partial class ShareCounts
{
  [System.Text.Json.Serialization.JsonPropertyName("link_shares")]
  public int? LinkShares { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("team_shares")]
  public int? TeamShares { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user_shares")]
  public int? UserShares { get; set; }
}
