//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Vikunja.Models;

[JsonConverter(typeof(JsonNumberEnumConverter<SharingType>))]
public enum SharingType
{
    SharingTypeUnknown = 0,
    SharingTypeWithoutPassword = 1,
    SharingTypeWithPassword = 2,
}
