//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

namespace Apigen.Vikunja.Models;

[JsonConverter(typeof(JsonNumberEnumConverter<Status>))]
public enum Status
{
    StatusActive = 0,
    StatusEmailConfirmationRequired = 1,
    StatusDisabled = 2,
    StatusAccountLocked = 3,
}
