//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// migration.Status from OpenAPI schema.
/// Schema path: #/components/schemas/migration.Status
/// </summary>
public partial class Status
{
  [System.Text.Json.Serialization.JsonPropertyName("finished_at")]
  public string? FinishedAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("migrator_name")]
  public string? MigratorName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("started_at")]
  public string? StartedAt { get; set; }
}
