//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Subscription from OpenAPI schema.
/// Schema path: #/components/schemas/models.Subscription
/// </summary>
public class Subscription
{
  /// <summary>
  /// A timestamp when this subscription was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("entity")]
  public int? Entity { get; set; }

  /// <summary>
  /// The id of the entity to subscribe to.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("entity_id")]
  public int? EntityId { get; set; }

  /// <summary>
  /// The numeric ID of the subscription
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }
}
