//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskPosition from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskPosition
/// </summary>
public partial class TaskPosition
{
  /// <summary>
  /// The position of the task - any task project can be sorted as usual by this parameter.
  /// When accessing tasks via kanban buckets, this is primarily used to sort them based on a range
  /// We&apos;re using a float64 here to make it possible to put any task within any two other tasks (by changing the number).
  /// You would calculate the new position between two tasks with something like task3.position = (task2.position - task1.position) / 2.
  /// A 64-Bit float leaves plenty of room to initially give tasks a position with 2^16 difference to the previous task
  /// which also leaves a lot of room for rearranging and sorting later.
  /// Positions are always saved per view. They will automatically be set if you request the tasks through a view
  /// endpoint, otherwise they will always be 0. To update them, take a look at the Task Position endpoint.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("position")]
  public decimal? Position { get; set; }

  /// <summary>
  /// The project view this task is related to
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_view_id")]
  public int? ProjectViewId { get; set; }

  /// <summary>
  /// The ID of the task this position is for
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public int? TaskId { get; set; }
}
