//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskRelation from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskRelation
/// </summary>
public class TaskRelation
{
  /// <summary>
  /// A timestamp when this label was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who created this relation
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The ID of the other task, the task which is being related.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("other_task_id")]
  public int? OtherTaskId { get; set; }

  /// <summary>
  /// The kind of the relation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("relation_kind")]
  public RelationKind? RelationKind { get; set; }

  /// <summary>
  /// The ID of the &quot;base&quot; task, the task which has a relation to another.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public int? TaskId { get; set; }
}
