//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskBucket from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskBucket
/// </summary>
public partial class TaskBucket
{
  [System.Text.Json.Serialization.JsonPropertyName("bucket")]
  public Bucket? Bucket { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bucket_id")]
  public int? BucketId { get; set; }

  /// <summary>
  /// The view this bucket belongs to. Combined with TaskID this forms a
  /// unique index.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_view_id")]
  public int? ProjectViewId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task")]
  public TaskItem? Task { get; set; }

  /// <summary>
  /// The task which belongs to the bucket. Together with ProjectViewID
  /// this field is part of a unique index to prevent duplicates.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public int? TaskId { get; set; }
}
