//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskReminder from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskReminder
/// </summary>
public class TaskReminder
{
  /// <summary>
  /// A period in seconds relative to another date argument. Negative values mean the reminder triggers before the date. Default: 0, tiggers when RelativeTo is due.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("relative_period")]
  public int? RelativePeriod { get; set; }

  /// <summary>
  /// The name of the date field to which the relative period refers to.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("relative_to")]
  public ReminderRelation? RelativeTo { get; set; }

  /// <summary>
  /// The absolute time when the user wants to be reminded of the task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminder")]
  public string? Reminder { get; set; }
}
