//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Task from OpenAPI schema.
/// Schema path: #/components/schemas/models.Task
/// </summary>
public class TaskItem
{
  /// <summary>
  /// An array of users who are assigned to this task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assignees")]
  public List<User>? Assignees { get; set; }

  /// <summary>
  /// All attachments this task has. This property is read-onlym, you must use the separate endpoint to add attachments to a task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("attachments")]
  public List<TaskAttachment>? Attachments { get; set; }

  /// <summary>
  /// The bucket id. Will only be populated when the task is accessed via a view with buckets.
  /// Can be used to move a task between buckets. In that case, the new bucket must be in the same view as the old one.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bucket_id")]
  public int? BucketId { get; set; }

  /// <summary>
  /// All buckets across all views this task is part of. Only present when fetching tasks with the expand parameter set to buckets.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("buckets")]
  public List<Bucket>? Buckets { get; set; }

  /// <summary>
  /// Comment count of this task. Only present when fetching tasks with the expand parameter set to comment_count.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("comment_count")]
  public int? CommentCount { get; set; }

  /// <summary>
  /// All comments of this task. Only present when fetching tasks with the expand parameter set to comments.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("comments")]
  public List<TaskComment>? Comments { get; set; }

  /// <summary>
  /// If this task has a cover image, the field will return the id of the attachment that is the cover image.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("cover_image_attachment_id")]
  public int? CoverImageAttachmentId { get; set; }

  /// <summary>
  /// A timestamp when this task was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who initially created the task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The task description.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// Whether a task is done or not.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("done")]
  public bool? Done { get; set; }

  /// <summary>
  /// The time when a task was marked as done. This field is system-controlled and cannot be set via API.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("done_at")]
  public string? DoneAt { get; set; }

  /// <summary>
  /// The time when the task is due.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("due_date")]
  public string? DueDate { get; set; }

  /// <summary>
  /// When this task ends.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("end_date")]
  public string? EndDate { get; set; }

  /// <summary>
  /// The task color in hex
  /// </summary>
  [MaxLength(7)]
  [System.Text.Json.Serialization.JsonPropertyName("hex_color")]
  public string? HexColor { get; set; }

  /// <summary>
  /// The unique, numeric id of this task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The task identifier, based on the project identifier and the task&apos;s index
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  /// <summary>
  /// The task index, calculated per project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("index")]
  public int? Index { get; set; }

  /// <summary>
  /// True if a task is a favorite task. Favorite tasks show up in a separate &quot;Important&quot; project. This value depends on the user making the call to the api.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_favorite")]
  public bool? IsFavorite { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_unread")]
  public bool? IsUnread { get; set; }

  /// <summary>
  /// An array of labels which are associated with this task. This property is read-only, you must use the separate endpoint to add labels to a task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("labels")]
  public List<Label>? Labels { get; set; }

  /// <summary>
  /// Determines how far a task is left from being done
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("percent_done")]
  public decimal? PercentDone { get; set; }

  /// <summary>
  /// The position of the task - any task project can be sorted as usual by this parameter.
  /// When accessing tasks via views with buckets, this is primarily used to sort them based on a range.
  /// Positions are always saved per view. They will automatically be set if you request the tasks through a view
  /// endpoint, otherwise they will always be 0. To update them, take a look at the Task Position endpoint.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("position")]
  public decimal? Position { get; set; }

  /// <summary>
  /// The task priority. Can be anything you want, it is possible to sort by this later.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }

  /// <summary>
  /// The project this task belongs to.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public int? ProjectId { get; set; }

  /// <summary>
  /// Reactions on that task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reactions")]
  public ReactionMap? Reactions { get; set; }

  /// <summary>
  /// All related tasks, grouped by their relation kind
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("related_tasks")]
  public RelatedTaskMap? RelatedTasks { get; set; }

  /// <summary>
  /// An array of reminders that are associated with this task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminders")]
  public List<TaskReminder>? Reminders { get; set; }

  /// <summary>
  /// An amount in seconds this task repeats itself. If this is set, when marking the task as done, it will mark itself as &quot;undone&quot; and then increase all remindes and the due date by its amount.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("repeat_after")]
  public int? RepeatAfter { get; set; }

  /// <summary>
  /// Can have three possible values which will trigger when the task is marked as done: 0 = repeats after the amount specified in repeat_after, 1 = repeats all dates each months (ignoring repeat_after), 3 = repeats from the current date rather than the last set date.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("repeat_mode")]
  public TaskRepeatMode? RepeatMode { get; set; }

  /// <summary>
  /// When this task starts.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("start_date")]
  public string? StartDate { get; set; }

  /// <summary>
  /// The subscription status for the user reading this task. You can only read this property, use the subscription endpoints to modify it.
  /// Will only returned when retrieving one task.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("subscription")]
  public Subscription? Subscription { get; set; }

  /// <summary>
  /// The task text. This is what you&apos;ll see in the project.
  /// </summary>
  [MinLength(1)]
  [System.Text.Json.Serialization.JsonPropertyName("title")]
  public string? Title { get; set; }

  /// <summary>
  /// A timestamp when this task was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
