//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskAttachment from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskAttachment
/// </summary>
public partial class TaskAttachment
{
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("file")]
  public FileAttachment? File { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public int? TaskId { get; set; }
}
