//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskComment from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskComment
/// </summary>
public partial class TaskComment
{
  [System.Text.Json.Serialization.JsonPropertyName("author")]
  public User? Author { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("comment")]
  public string? Comment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("reactions")]
  public ReactionMap? Reactions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
