//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TaskCollection from OpenAPI schema.
/// Schema path: #/components/schemas/models.TaskCollection
/// </summary>
public class TaskCollection
{
  /// <summary>
  /// The filter query to match tasks by. Check out https://vikunja.io/docs/filters for a full explanation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filter")]
  public string? Filter { get; set; }

  /// <summary>
  /// If set to true, the result will also include null values
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("filter_include_nulls")]
  public bool? FilterIncludeNulls { get; set; }

  /// <summary>
  /// The query parameter to order the items by. This can be either asc or desc, with asc being the default.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("order_by")]
  public List<string?>? OrderBy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("s")]
  public string? S { get; set; }

  /// <summary>
  /// The query parameter to sort by. This is for ex. done, priority, etc.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sort_by")]
  public List<string?>? SortBy { get; set; }
}
