//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TeamProject from OpenAPI schema.
/// Schema path: #/components/schemas/models.TeamProject
/// </summary>
public class TeamProject
{
  /// <summary>
  /// A timestamp when this relation was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The unique, numeric id of this project &lt;-&gt; team relation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The permission this team has. 0 = Read only, 1 = Read &amp; Write, 2 = Admin. See the docs for more details.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("permission")]
  public Permission? Permission { get; set; }

  /// <summary>
  /// The team id.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("team_id")]
  public int? TeamId { get; set; }

  /// <summary>
  /// A timestamp when this relation was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
