//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TeamWithPermission from OpenAPI schema.
/// Schema path: #/components/schemas/models.TeamWithPermission
/// </summary>
public class TeamWithPermission
{
  /// <summary>
  /// A timestamp when this relation was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who created this team.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The team&apos;s description.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The team&apos;s external id provided by the openid or ldap provider
  /// </summary>
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("external_id")]
  public string? ExternalId { get; set; }

  /// <summary>
  /// The unique, numeric id of this team.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// Query parameter controlling whether to include public projects or not
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("include_public")]
  public bool? IncludePublic { get; set; }

  /// <summary>
  /// Defines wether the team should be publicly discoverable when sharing a project
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_public")]
  public bool? IsPublic { get; set; }

  /// <summary>
  /// An array of all members in this team.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("members")]
  public List<TeamUser>? Members { get; set; }

  /// <summary>
  /// The name of this team.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("permission")]
  public Permission? Permission { get; set; }

  /// <summary>
  /// A timestamp when this relation was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }
}
