//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TeamUser from OpenAPI schema.
/// Schema path: #/components/schemas/models.TeamUser
/// </summary>
public partial class TeamUser
{
  /// <summary>
  /// Whether the member is an admin of the team. See the docs for more about what a team admin can do
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("admin")]
  public bool? Admin { get; set; }

  /// <summary>
  /// A timestamp when this task was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user&apos;s email address.
  /// </summary>
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The unique, numeric id of this user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The full name of the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// A timestamp when this task was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }

  /// <summary>
  /// The username of the user. Is always unique.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
