//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.TeamMember from OpenAPI schema.
/// Schema path: #/components/schemas/models.TeamMember
/// </summary>
public class TeamMember
{
  /// <summary>
  /// Whether or not the member is an admin of the team. See the docs for more about what a team admin can do
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("admin")]
  public bool? Admin { get; set; }

  /// <summary>
  /// A timestamp when this relation was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The unique, numeric id of this team member relation.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The username of the member. We use this to prevent automated user id entering.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
