//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// user.TOTP from OpenAPI schema.
/// Schema path: #/components/schemas/user.TOTP
/// </summary>
public class Totp
{
  /// <summary>
  /// The totp entry will only be enabled after the user verified they have a working totp setup.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  /// <summary>
  /// The totp url used to be able to enroll the user later
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }
}
