//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.UserSettings from OpenAPI schema.
/// Schema path: #/components/schemas/v1.UserSettings
/// </summary>
public class UserSettings
{
  /// <summary>
  /// If a task is created without a specified project this value should be used. Applies
  /// to tasks made directly in API and from clients.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("default_project_id")]
  public int? DefaultProjectId { get; set; }

  /// <summary>
  /// If true, the user can be found when searching for their exact email.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("discoverable_by_email")]
  public bool? DiscoverableByEmail { get; set; }

  /// <summary>
  /// If true, this user can be found by their name or parts of it when searching for it.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("discoverable_by_name")]
  public bool? DiscoverableByName { get; set; }

  /// <summary>
  /// If enabled, sends email reminders of tasks to the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("email_reminders_enabled")]
  public bool? EmailRemindersEnabled { get; set; }

  /// <summary>
  /// Additional settings links as provided by openid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("extra_settings_links")]
  public Dictionary<string, object?>? ExtraSettingsLinks { get; set; }

  /// <summary>
  /// Additional settings only used by the frontend
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("frontend_settings")]
  public object? FrontendSettings { get; set; }

  /// <summary>
  /// The user&apos;s language
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  /// <summary>
  /// The new name of the current user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// If enabled, the user will get an email for their overdue tasks each morning.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("overdue_tasks_reminders_enabled")]
  public bool? OverdueTasksRemindersEnabled { get; set; }

  /// <summary>
  /// The time when the daily summary of overdue tasks will be sent via email.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("overdue_tasks_reminders_time")]
  public string? OverdueTasksRemindersTime { get; set; }

  /// <summary>
  /// The user&apos;s time zone. Used to send task reminders in the time zone of the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("timezone")]
  public string? Timezone { get; set; }

  /// <summary>
  /// The day when the week starts for this user. 0 = sunday, 1 = monday, etc.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("week_start")]
  public int? WeekStart { get; set; }
}
