//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.UserRegister from OpenAPI schema.
/// Schema path: #/components/schemas/v1.UserRegister
/// </summary>
public class UserRegister
{
  /// <summary>
  /// The user&apos;s email address
  /// </summary>
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The language of the new user. Must be a valid IETF BCP 47 language code and exist in Vikunja.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  /// <summary>
  /// The user&apos;s password in clear text. Only used when registering the user. The maximum limi is 72 bytes, which may be less than 72 characters. This is due to the limit in the bcrypt hashing algorithm used to store passwords in Vikunja.
  /// </summary>
  [MinLength(8)]
  [MaxLength(72)]
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The user&apos;s username. Cannot contain anything that looks like an url or whitespaces.
  /// </summary>
  [MinLength(3)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
