//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.UserWithSettings from OpenAPI schema.
/// Schema path: #/components/schemas/v1.UserWithSettings
/// </summary>
public partial class UserWithSettings
{
  [System.Text.Json.Serialization.JsonPropertyName("auth_provider")]
  public string? AuthProvider { get; set; }

  /// <summary>
  /// BotOwnerID is the ID of the owning (human) user if this user is a bot.
  /// A non-zero value means this user is a bot and cannot authenticate via password.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bot_owner_id")]
  public int? BotOwnerId { get; set; }

  /// <summary>
  /// A timestamp when this task was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deletion_scheduled_at")]
  public string? DeletionScheduledAt { get; set; }

  /// <summary>
  /// The user&apos;s email address.
  /// </summary>
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The unique, numeric id of this user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_admin")]
  public bool? IsAdmin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_local_user")]
  public bool? IsLocalUser { get; set; }

  /// <summary>
  /// The full name of the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("pending_email")]
  public string? PendingEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public UserGeneralSettings? Settings { get; set; }

  /// <summary>
  /// A timestamp when this task was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }

  /// <summary>
  /// The username of the user. Is always unique.
  /// </summary>
  [MinLength(1)]
  [MaxLength(250)]
  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }
}
