//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.UserGeneralSettings from OpenAPI schema.
/// Schema path: #/components/schemas/models.UserGeneralSettings
/// </summary>
public partial class UserGeneralSettings
{
  [System.Text.Json.Serialization.JsonPropertyName("default_project_id")]
  public int? DefaultProjectId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("discoverable_by_email")]
  public bool? DiscoverableByEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("discoverable_by_name")]
  public bool? DiscoverableByName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email_reminders_enabled")]
  public bool? EmailRemindersEnabled { get; set; }

  /// <summary>
  /// Server/OpenID-provided; populated on read, ignored on write.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("extra_settings_links")]
  public Dictionary<string, object?>? ExtraSettingsLinks { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("frontend_settings")]
  public object? FrontendSettings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("language")]
  public string? Language { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overdue_tasks_reminders_enabled")]
  public bool? OverdueTasksRemindersEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("overdue_tasks_reminders_time")]
  public string? OverdueTasksRemindersTime { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("timezone")]
  public string? Timezone { get; set; }

  [Range(0, 6)]
  [System.Text.Json.Serialization.JsonPropertyName("week_start")]
  public int? WeekStart { get; set; }
}
