//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.UserAvatarProvider from OpenAPI schema.
/// Schema path: #/components/schemas/v1.UserAvatarProvider
/// </summary>
public class UserAvatarProvider
{
  /// <summary>
  /// The avatar provider. Valid types are gravatar (uses the user email), upload, initials, marble (generates a random avatar for each user), ldap (synced from LDAP server), openid (synced from OpenID provider), default.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("avatar_provider")]
  public string? AvatarProvider { get; set; }
}
