//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v1.0.0-rc2-268-9990a1f6
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// v1.vikunjaInfos from OpenAPI schema.
/// Schema path: #/components/schemas/v1.vikunjaInfos
/// </summary>
public class VikunjaInfos
{
  [System.Text.Json.Serialization.JsonPropertyName("auth")]
  public AuthInfo? Auth { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("available_migrators")]
  public List<string?>? AvailableMigrators { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("caldav_enabled")]
  public bool? CaldavEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("demo_mode_enabled")]
  public bool? DemoModeEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email_reminders_enabled")]
  public bool? EmailRemindersEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled_background_providers")]
  public List<string?>? EnabledBackgroundProviders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("frontend_url")]
  public string? FrontendUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("legal")]
  public LegalInfo? Legal { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("link_sharing_enabled")]
  public bool? LinkSharingEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_file_size")]
  public string? MaxFileSize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("max_items_per_page")]
  public int? MaxItemsPerPage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("motd")]
  public string? Motd { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("public_teams_enabled")]
  public bool? PublicTeamsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_attachments_enabled")]
  public bool? TaskAttachmentsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task_comments_enabled")]
  public bool? TaskCommentsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totp_enabled")]
  public bool? TotpEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user_deletion_enabled")]
  public bool? UserDeletionEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("version")]
  public string? Version { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webhooks_enabled")]
  public bool? WebhooksEnabled { get; set; }
}
