//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja-patched.json
// API: Vikunja API
// Version: v2.3.0-34-540beefa
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Vikunja.Models;

/// <summary>
/// models.Webhook from OpenAPI schema.
/// Schema path: #/components/schemas/models.Webhook
/// </summary>
public partial class Webhook
{
  [System.Text.Json.Serialization.JsonPropertyName("basic_auth_password")]
  public string? BasicAuthPassword { get; set; }

  /// <summary>
  /// If provided, webhook requests will be sent with a Basic Auth header.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("basic_auth_user")]
  public string? BasicAuthUser { get; set; }

  /// <summary>
  /// A timestamp when this webhook target was created. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created")]
  public string? Created { get; set; }

  /// <summary>
  /// The user who initially created the webhook target.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("created_by")]
  public User? CreatedBy { get; set; }

  /// <summary>
  /// The webhook events which should fire this webhook target
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("events")]
  public List<string?>? Events { get; set; }

  /// <summary>
  /// The generated ID of this webhook target
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public int? Id { get; set; }

  /// <summary>
  /// The project ID of the project this webhook target belongs to
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public int? ProjectId { get; set; }

  /// <summary>
  /// If provided, webhook requests will be signed using HMAC. Check out the docs about how to use this: https://vikunja.io/docs/webhooks/#signing
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  /// <summary>
  /// The target URL where the POST request with the webhook payload will be made
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("target_url")]
  public string? TargetUrl { get; set; }

  /// <summary>
  /// A timestamp when this webhook target was last updated. You cannot change this value.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("updated")]
  public string? Updated { get; set; }

  /// <summary>
  /// The user ID if this is a user-level webhook (mutually exclusive with ProjectID)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public int? UserId { get; set; }
}
