//
// <auto-generated>
// Vikunja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/vikunja.json
// API: Vikunja API
// Version: v2.6.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Vikunja.Client;

/// <summary>
/// Request parameters for Delete a user (admin)
/// Operation: DELETE /admin/users/{id}
/// </summary>
public partial class DeleteadminRequest : BaseRequest
{
  /// <summary>
  /// Deletion mode: &apos;now&apos; for immediate deletion, &apos;scheduled&apos; (default) to trigger the email-confirmation self-deletion flow.
  /// </summary>
  [JsonPropertyName("mode")]
  public string? Mode { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Mode != null)
      queryParams["mode"] = Mode;

    return queryParams.ToQueryString();
  }
}
